- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: webapp
    api_version: v1
    kind: Namespace
    state: present

- name: Create the Deployment
  kubernetes.core.k8s:
    state: present
    template: deployment.yml

- name: Create the service
  kubernetes.core.k8s:
    state: present
    template: service.yml